# Generated by Django 5.1.6 on 2025-05-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='approved',
        ),
    ]
