# Generated by Django 5.1.6 on 2025-05-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='theme_preference',
        ),
    ]
