# Generated by Django 5.1.6 on 2025-05-26 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0009_serviceprovider_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=100),
        ),
    ]
