# Generated by Django 5.1.6 on 2025-05-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0010_alter_servicebooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='revenue',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='allservices.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('wall-painting', 'Wall Painting'), ('exterior-painting', 'Exterior Painting'), ('ceiling-painting', 'Ceiling Painting'), ('touch-up', 'Touch Up'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('wooden-flooring', 'Wooden Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance'), ('washing-machine', 'Washing Machine'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('wall-painting', 'Wall Painting'), ('exterior-painting', 'Exterior Painting'), ('ceiling-painting', 'Ceiling Painting'), ('touch-up', 'Touch Up'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('wooden-flooring', 'Wooden Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('appliance', 'Appliance'), ('washing-machine', 'Washing Machine'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=100),
        ),
    ]
