# Generated by Django 5.1.6 on 2025-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0012_alter_servicebooking_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('wall-painting', 'Wall Painting'), ('exterior-painting', 'Exterior Painting'), ('ceiling-painting', 'Ceiling Painting'), ('touch-up', 'Touch Up'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('wooden-flooring', 'Wooden Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('bathroom-fixtures', 'Bathroom Fixtures'), ('sewer-line-repair', 'Sewer Line Repair'), ('pipe-repair', 'Pipe Repair'), ('drain-cleaning', 'Drain Cleaning'), ('water-heater-service', 'Water Heater Service'), ('water-heater-installation', 'Water Heater Installation'), ('water-heater-repair', 'Water Heater Repair'), ('faucet-repair', 'Faucet Repair'), ('toilet-repair', 'Toilet Repair'), ('sink-installation', 'Sink Installation'), ('leak-repair', 'Leak Repair'), ('pipe-installation', 'Pipe Installation'), ('appliance', 'Appliance'), ('washing-machine', 'Washing Machine'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('painting', 'Painting'), ('wall-painting', 'Wall Painting'), ('exterior-painting', 'Exterior Painting'), ('ceiling-painting', 'Ceiling Painting'), ('touch-up', 'Touch Up'), ('roofing', 'Roofing'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('wooden-flooring', 'Wooden Flooring'), ('plastering', 'Plastering'), ('plumbing', 'Plumbing'), ('bathroom-fixtures', 'Bathroom Fixtures'), ('sewer-line-repair', 'Sewer Line Repair'), ('pipe-repair', 'Pipe Repair'), ('drain-cleaning', 'Drain Cleaning'), ('water-heater-service', 'Water Heater Service'), ('water-heater-installation', 'Water Heater Installation'), ('water-heater-repair', 'Water Heater Repair'), ('faucet-repair', 'Faucet Repair'), ('toilet-repair', 'Toilet Repair'), ('sink-installation', 'Sink Installation'), ('leak-repair', 'Leak Repair'), ('pipe-installation', 'Pipe Installation'), ('appliance', 'Appliance'), ('washing-machine', 'Washing Machine'), ('water-heater', 'Water Heater'), ('gardening', 'Gardening')], max_length=100),
        ),
    ]
