# Generated by Django 5.1.6 on 2025-05-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allservices', '0014_servicebooking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allservices_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovider',
            unique_together={('user',)},
        ),
    ]
